---
apiVersion: v1
kind: Secret
metadata:
  name: simple-secret
  annotations:
    avp.kubernetes.io/path: '\Personal Folders\cloudadmin\test-avp'
type: Opaque
stringData:
  username: <username>
  password: <password>
