---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-secret
  namespace: argocd-avp-gitops
spec:
  destination:
    namespace: argocd-avp-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/jtudelag/argocd-vault-plugin-demo.git'
    targetRevision: HEAD
    path: secrets/simple/
  #syncPolicy:
  #  syncOptions:
  #  - CreateNamespace=true
